// <auto-generated />
namespace TDD.Blog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205091215234_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozdPn46flNXF+FW+qpqireoibz5Kj8siI2Re5+X5e2K28xCYfWT7pF5PCbv2+s31KueeP/voZdW0fgtq83vl18EH9NHLulrldXv9Kj/33jubfZTeDd+9233Zvtp5Dyh89tHZsv10/6P0xboss0lJH5xnZZN/lK4+ffSaxp9/ni/zOmvz2cusbfOa5udslvMQlBSPVp/ejhoP7+7sgRp3s+WyarOWJruHfAfVN0Vb5gbT121NjPNR+qx4l8+e58uLdm6x/SJ7Zz7Z39kh/vlqWRCj0Vttvc794cnfnW5fZJfFBWPUQeCkWixotMQDr/KSGzTzYiWsMNYvf3+ewPRZXS1eVaV7iT///d9k9UVOX7+pIl++rtb1tIPO47uOQzbyjUL6Oqyjr34d7vFe/f8AAx2v23lV/xA4qEelZYu5+aF3fDvhvi37C2d/XdY33B1lfSMXt2H946appgXjEHKh9B8O5nQ5SzchIxPiDYKmYF22xaosptT3Zx99q0efAZBWtB1IoUcIbzdEkOB9uXyal3mbp8fTlk3eSdZMs1l/Yoges/ATkuG8hvhkJfFY09ZZsWz7Al8sp8UqKzdg3XnnPSwM8LI9dL95mq/yJeR7wxx8WNe2hw6pbqLM47seG/UVKySW3shrDwHrBVz3eAyvvM5brzHZCMe9ATv0uCl82dmY3vuWQzsgvJH04KhMek1iMtsl6w1SY3H20e3NzQ1y4gFRgnXZPRxXRDPYWbLfPb4rbpx+8PjugL/3+ItstSIl7Pl/+kn6Wpy/k+3X7+/dLQTG3WkTcfIstrYn4qXsIu98C3LN8mdF3bRPszabZFDRJ7NFr9nteNJ05rNmf6YMp5nW+F2drpgTLKzcl1x9/RkNCxPOI9Tx2Ynuv5bC+c7KrB6wXidVuV4sN2uCYSjqNfpA9KM+jMd3OyPo6ZseqXoqOqT7rWbFCtGHT0zUDWRYN83N4JtDhPV8P5+4g97kJljGM/MBmc9uD8X6WSE++uHt4bwf4/2sMk1P1XWb2N6tyuuotseqZgL9l8bi3Z7ekSYfpUSey2IGnfP6umnzxRgNxq9/Ufk6rymgP8nH+4jSTbMvsmVxnjftm+ptTuaGv/u6QbP18ptmVv6/OXKeFBcFuOzGKOcm93tT0Lu8zOrpPKsjccKmwOD/a0HkzxYtw/jvaxIzhn8Q3n1jcOMMtnHM33DMJM7jDzOi6TmNXy9G+1qB0YBTc1uNgfG8byT0gd1ZqB2yfsPRT98h7U5aPwAajH/EqHz20WxS0dwKJ8cDgC5YO/s9yPabGPChEOVnNW7ySeBc31sESbHo6mcnNOr7BcQ466XNlhPPNsWFA4Hc+TKfBixj25wtzyvDuR2MnuYNN+loty/yNpsRPx3XbXGeTVv6epo3DWfGfjIr19TkdDHJZ2fLL9ftat3SkPPFpLz2iQEJ2NQ/x38hzo+/XHH26psYAqFZ0BDyL5dP1kU5s3g/iyjmARAQLbVwmMsWlu7i2kJ6US1vCUjJ99RohDf5YkWJurz5cvk6u8yHcbuZhiHFHj8tsos6W/gUlE8Uk9cZ9ex1QR34b7j+6E9iV1qqOfp/AgAA//+9NqsnHxoAAA=="; }
        }
    }
}
